### ISSUE TITLE
Error on `$ kubectl apply -f mysql-secret.yaml`

### ISSUE THREAD

**Issue by mbbroberg** [clcollins/working-with-kubernetes-secrets-and-configmaps#1]
I get the following: 

```
error: SchemaError(io.k8s.api.admissionregistration.v1beta1.ServiceReference): invalid object doesn't have additional properties
```

**Comment by mbbroberg** [comment]
Huh, this resolved it: 

https://stackoverflow.com/questions/55417410/kubernetes-create-deployment-unexpected-schemaerror

```
$ rm /usr/local/bin/kubectl
$ brew link --overwrite kubernetes-cli
```

Might be worth noting in the article.. I'm thinking on it :)

**Comment by clcollins** [comment]
Nice.  Looks like the kubectl packaged with Docker is not matching your cluster version?  Thaaaaanks Docker... 🙄

I guess this would be true of any kubectl/cluster version mismatch.
