### ISSUE TITLE
base64 has no -d option 

### ISSUE THREAD

**Issue by mbbroberg** [clcollins/working-with-kubernetes-secrets-and-configmaps#2]
On my MacOS configuration, base64 doesn't have a `-d`. I adjusted to `-D` or `--decode` and it ran properly.

**Comment by clcollins** [comment]
Cool, yeah, I'm using the version shipping in Fedora.  I don't have a Mac to test with but I can make a note.  Thanks!

**Comment by clcollins** [comment]
Fixed by #3
